server {
    # Listen on port 8080 to match Google Cloud Run's default port expectation
    listen       8080;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Enable HTML5 History API fallback for React Router
        try_files $uri $uri/ /index.html;
    }

    # Redirect server error pages to the static page /50x.html
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
